# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'book.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BookedWindow(object):
    def setupUi(self, BookedWindow):
        BookedWindow.setObjectName("BookedWindow")
        BookedWindow.resize(598, 363)
        self.centralwidget = QtWidgets.QWidget(BookedWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 571, 192))
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 10, 261, 16))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(0, 300, 621, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 270, 181, 20))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(240, 270, 301, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 240, 231, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 240, 231, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        BookedWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(BookedWindow)
        self.statusbar.setObjectName("statusbar")
        BookedWindow.setStatusBar(self.statusbar)

        self.retranslateUi(BookedWindow)
        QtCore.QMetaObject.connectSlotsByName(BookedWindow)

    def retranslateUi(self, BookedWindow):
        _translate = QtCore.QCoreApplication.translate
        BookedWindow.setWindowTitle(_translate("BookedWindow", "MainWindow"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("BookedWindow", "Ticket1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("BookedWindow", "Ticket2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("BookedWindow", "Ticket3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("BookedWindow", "Ticket4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("BookedWindow", "Ticket5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("BookedWindow", "Ticket6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("BookedWindow", "Ticket7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("BookedWindow", "Ticket8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("BookedWindow", "Ticket9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("BookedWindow", "Ticket10"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("BookedWindow", "CustomerName:"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("BookedWindow", "DepartureFrom:"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("BookedWindow", "ArrivalAt:"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("BookedWindow", "TravelClass:"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("BookedWindow", "Prices(In USD):"))
        self.label.setText(_translate("BookedWindow", "Booked Tickets"))
        self.commandLinkButton.setText(_translate("BookedWindow", "Email Ticket To Customer"))
        self.label_2.setText(_translate("BookedWindow", "Confirm Customers\' Email Address: "))
        self.pushButton.setText(_translate("BookedWindow", "Load Tickets"))
        self.pushButton_2.setText(_translate("BookedWindow", "Cancel/Go To Main Window"))

