# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customerdetails.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CustomerWindow(object):
    def setupUi(self, CustomerWindow):
        CustomerWindow.setObjectName("CustomerWindow")
        CustomerWindow.resize(541, 533)
        self.centralwidget = QtWidgets.QWidget(CustomerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 40, 224, 351))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cname = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.cname.setObjectName("cname")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cname)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cid = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.cid.setObjectName("cid")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cid)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.fathername = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fathername.setObjectName("fathername")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fathername)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.genderbutton1 = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.genderbutton1.setObjectName("genderbutton1")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.genderbutton1)
        self.genderbutton2 = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.genderbutton2.setObjectName("genderbutton2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.genderbutton2)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.dateEdit = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.phonenumber = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.phonenumber.setObjectName("phonenumber")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.phonenumber)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.address = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.address.setObjectName("address")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.address)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(90, 10, 361, 16))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.imagebutton = QtWidgets.QPushButton(self.centralwidget)
        self.imagebutton.setGeometry(QtCore.QRect(334, 260, 91, 23))
        self.imagebutton.setObjectName("imagebutton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 40, 221, 201))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.cancelbutton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.cancelbutton.setGeometry(QtCore.QRect(120, 430, 141, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelbutton.setIcon(icon)
        self.cancelbutton.setObjectName("cancelbutton")
        self.submitbutton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.submitbutton.setGeometry(QtCore.QRect(290, 430, 131, 41))
        self.submitbutton.setObjectName("submitbutton")
        CustomerWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(CustomerWindow)
        self.statusbar.setObjectName("statusbar")
        CustomerWindow.setStatusBar(self.statusbar)
        self.actionShow_Customers = QtWidgets.QAction(CustomerWindow)
        self.actionShow_Customers.setObjectName("actionShow_Customers")
        self.actionUpdate_Customers = QtWidgets.QAction(CustomerWindow)
        self.actionUpdate_Customers.setObjectName("actionUpdate_Customers")
        self.actionDelete_Customers = QtWidgets.QAction(CustomerWindow)
        self.actionDelete_Customers.setObjectName("actionDelete_Customers")
        self.actionSearch_Customers = QtWidgets.QAction(CustomerWindow)
        self.actionSearch_Customers.setObjectName("actionSearch_Customers")

        self.retranslateUi(CustomerWindow)
        QtCore.QMetaObject.connectSlotsByName(CustomerWindow)

    def retranslateUi(self, CustomerWindow):
        _translate = QtCore.QCoreApplication.translate
        CustomerWindow.setWindowTitle(_translate("CustomerWindow", "MainWindow"))
        self.label.setText(_translate("CustomerWindow", "Customer Name: "))
        self.label_3.setText(_translate("CustomerWindow", "Customer ID:"))
        self.label_4.setText(_translate("CustomerWindow", "Father\'s Name:"))
        self.label_5.setText(_translate("CustomerWindow", "Gender:"))
        self.genderbutton1.setText(_translate("CustomerWindow", "Male"))
        self.genderbutton2.setText(_translate("CustomerWindow", "Female"))
        self.label_6.setText(_translate("CustomerWindow", "DOB:"))
        self.label_7.setText(_translate("CustomerWindow", "Phone Numbe:r"))
        self.label_8.setText(_translate("CustomerWindow", "Address:"))
        self.label_9.setText(_translate("CustomerWindow", "CUSTOMER DETAILS!"))
        self.imagebutton.setText(_translate("CustomerWindow", "ChooseAnImage!"))
        self.cancelbutton.setText(_translate("CustomerWindow", "Back"))
        self.submitbutton.setText(_translate("CustomerWindow", "Submit"))
        self.actionShow_Customers.setText(_translate("CustomerWindow", "Show Customers!"))
        self.actionUpdate_Customers.setText(_translate("CustomerWindow", "Update Customers!"))
        self.actionDelete_Customers.setText(_translate("CustomerWindow", "Delete Customers!"))
        self.actionSearch_Customers.setText(_translate("CustomerWindow", "Search Customers!"))

