# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flightoptions.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FlightOptionsWindow(object):
    def setupUi(self, FlightOptionsWindow):
        FlightOptionsWindow.setObjectName("FlightOptionsWindow")
        FlightOptionsWindow.resize(952, 564)
        self.centralwidget = QtWidgets.QWidget(FlightOptionsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(340, 50, 601, 192))
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(50)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(40, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(41, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(42, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(43, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(44, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(45, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(46, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(47, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(48, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(49, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 30, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 260, 91, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 500, 121, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(740, 500, 121, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(520, 10, 261, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 350, 81, 20))
        self.label_4.setObjectName("label_4")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(120, 350, 201, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 400, 91, 20))
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(120, 400, 201, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 450, 91, 20))
        self.label_6.setObjectName("label_6")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(120, 450, 201, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 500, 121, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 311, 281))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("Amadeus.jpg"))
        self.label_7.setObjectName("label_7")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(340, 280, 601, 192))
        self.tableWidget_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_2.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(50)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(40, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(41, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(42, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(43, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(44, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(45, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(46, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(47, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(48, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(49, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        FlightOptionsWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FlightOptionsWindow)
        self.statusbar.setObjectName("statusbar")
        FlightOptionsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(FlightOptionsWindow)
        QtCore.QMetaObject.connectSlotsByName(FlightOptionsWindow)

    def retranslateUi(self, FlightOptionsWindow):
        _translate = QtCore.QCoreApplication.translate
        FlightOptionsWindow.setWindowTitle(_translate("FlightOptionsWindow", "MainWindow"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("FlightOptionsWindow", "1."))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("FlightOptionsWindow", "2."))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("FlightOptionsWindow", "3."))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("FlightOptionsWindow", "4."))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("FlightOptionsWindow", "5."))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("FlightOptionsWindow", "6."))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("FlightOptionsWindow", "7."))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("FlightOptionsWindow", "8."))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("FlightOptionsWindow", "9."))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("FlightOptionsWindow", "10."))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("FlightOptionsWindow", "11."))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("FlightOptionsWindow", "12."))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("FlightOptionsWindow", "13."))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("FlightOptionsWindow", "14."))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("FlightOptionsWindow", "15."))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("FlightOptionsWindow", "16."))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("FlightOptionsWindow", "17."))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("FlightOptionsWindow", "18."))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("FlightOptionsWindow", "19."))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("FlightOptionsWindow", "20."))
        item = self.tableWidget.verticalHeaderItem(20)
        item.setText(_translate("FlightOptionsWindow", "21."))
        item = self.tableWidget.verticalHeaderItem(21)
        item.setText(_translate("FlightOptionsWindow", "22."))
        item = self.tableWidget.verticalHeaderItem(22)
        item.setText(_translate("FlightOptionsWindow", "23."))
        item = self.tableWidget.verticalHeaderItem(23)
        item.setText(_translate("FlightOptionsWindow", "24."))
        item = self.tableWidget.verticalHeaderItem(24)
        item.setText(_translate("FlightOptionsWindow", "25."))
        item = self.tableWidget.verticalHeaderItem(25)
        item.setText(_translate("FlightOptionsWindow", "26."))
        item = self.tableWidget.verticalHeaderItem(26)
        item.setText(_translate("FlightOptionsWindow", "27."))
        item = self.tableWidget.verticalHeaderItem(27)
        item.setText(_translate("FlightOptionsWindow", "28."))
        item = self.tableWidget.verticalHeaderItem(28)
        item.setText(_translate("FlightOptionsWindow", "29."))
        item = self.tableWidget.verticalHeaderItem(29)
        item.setText(_translate("FlightOptionsWindow", "30."))
        item = self.tableWidget.verticalHeaderItem(30)
        item.setText(_translate("FlightOptionsWindow", "31."))
        item = self.tableWidget.verticalHeaderItem(31)
        item.setText(_translate("FlightOptionsWindow", "32."))
        item = self.tableWidget.verticalHeaderItem(32)
        item.setText(_translate("FlightOptionsWindow", "33."))
        item = self.tableWidget.verticalHeaderItem(33)
        item.setText(_translate("FlightOptionsWindow", "34."))
        item = self.tableWidget.verticalHeaderItem(34)
        item.setText(_translate("FlightOptionsWindow", "35."))
        item = self.tableWidget.verticalHeaderItem(35)
        item.setText(_translate("FlightOptionsWindow", "36."))
        item = self.tableWidget.verticalHeaderItem(36)
        item.setText(_translate("FlightOptionsWindow", "37."))
        item = self.tableWidget.verticalHeaderItem(37)
        item.setText(_translate("FlightOptionsWindow", "38."))
        item = self.tableWidget.verticalHeaderItem(38)
        item.setText(_translate("FlightOptionsWindow", "39."))
        item = self.tableWidget.verticalHeaderItem(39)
        item.setText(_translate("FlightOptionsWindow", "40."))
        item = self.tableWidget.verticalHeaderItem(40)
        item.setText(_translate("FlightOptionsWindow", "41."))
        item = self.tableWidget.verticalHeaderItem(41)
        item.setText(_translate("FlightOptionsWindow", "42."))
        item = self.tableWidget.verticalHeaderItem(42)
        item.setText(_translate("FlightOptionsWindow", "43."))
        item = self.tableWidget.verticalHeaderItem(43)
        item.setText(_translate("FlightOptionsWindow", "44."))
        item = self.tableWidget.verticalHeaderItem(44)
        item.setText(_translate("FlightOptionsWindow", "45."))
        item = self.tableWidget.verticalHeaderItem(45)
        item.setText(_translate("FlightOptionsWindow", "46."))
        item = self.tableWidget.verticalHeaderItem(46)
        item.setText(_translate("FlightOptionsWindow", "47."))
        item = self.tableWidget.verticalHeaderItem(47)
        item.setText(_translate("FlightOptionsWindow", "48."))
        item = self.tableWidget.verticalHeaderItem(48)
        item.setText(_translate("FlightOptionsWindow", "49."))
        item = self.tableWidget.verticalHeaderItem(49)
        item.setText(_translate("FlightOptionsWindow", "50."))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FlightOptionsWindow", "Depart. From"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FlightOptionsWindow", "Depart. Time"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("FlightOptionsWindow", "Arrival At"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("FlightOptionsWindow", "Arrival Time"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("FlightOptionsWindow", "Aircraft No."))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("FlightOptionsWindow", "Travel Class"))
        self.label.setText(_translate("FlightOptionsWindow", "First Segment:"))
        self.label_2.setText(_translate("FlightOptionsWindow", "Second Segment:"))
        self.pushButton.setText(_translate("FlightOptionsWindow", "Book"))
        self.pushButton_2.setText(_translate("FlightOptionsWindow", "Cancel"))
        self.label_3.setText(_translate("FlightOptionsWindow", "Available Tickets"))
        self.label_4.setText(_translate("FlightOptionsWindow", "Departure Date:"))
        self.label_5.setText(_translate("FlightOptionsWindow", "Origin:"))
        self.comboBox.setItemText(0, _translate("FlightOptionsWindow", "ABV"))
        self.comboBox.setItemText(1, _translate("FlightOptionsWindow", "Option2"))
        self.label_6.setText(_translate("FlightOptionsWindow", "Destination:"))
        self.comboBox_2.setItemText(0, _translate("FlightOptionsWindow", "IAD"))
        self.comboBox_2.setItemText(1, _translate("FlightOptionsWindow", "Option2"))
        self.pushButton_3.setText(_translate("FlightOptionsWindow", "Search"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("FlightOptionsWindow", "1."))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("FlightOptionsWindow", "2."))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("FlightOptionsWindow", "3."))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("FlightOptionsWindow", "4."))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("FlightOptionsWindow", "5."))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("FlightOptionsWindow", "6."))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("FlightOptionsWindow", "7."))
        item = self.tableWidget_2.verticalHeaderItem(7)
        item.setText(_translate("FlightOptionsWindow", "8."))
        item = self.tableWidget_2.verticalHeaderItem(8)
        item.setText(_translate("FlightOptionsWindow", "9."))
        item = self.tableWidget_2.verticalHeaderItem(9)
        item.setText(_translate("FlightOptionsWindow", "10."))
        item = self.tableWidget_2.verticalHeaderItem(10)
        item.setText(_translate("FlightOptionsWindow", "11."))
        item = self.tableWidget_2.verticalHeaderItem(11)
        item.setText(_translate("FlightOptionsWindow", "12."))
        item = self.tableWidget_2.verticalHeaderItem(12)
        item.setText(_translate("FlightOptionsWindow", "13."))
        item = self.tableWidget_2.verticalHeaderItem(13)
        item.setText(_translate("FlightOptionsWindow", "14."))
        item = self.tableWidget_2.verticalHeaderItem(14)
        item.setText(_translate("FlightOptionsWindow", "15."))
        item = self.tableWidget_2.verticalHeaderItem(15)
        item.setText(_translate("FlightOptionsWindow", "16."))
        item = self.tableWidget_2.verticalHeaderItem(16)
        item.setText(_translate("FlightOptionsWindow", "17."))
        item = self.tableWidget_2.verticalHeaderItem(17)
        item.setText(_translate("FlightOptionsWindow", "18."))
        item = self.tableWidget_2.verticalHeaderItem(18)
        item.setText(_translate("FlightOptionsWindow", "19."))
        item = self.tableWidget_2.verticalHeaderItem(19)
        item.setText(_translate("FlightOptionsWindow", "20."))
        item = self.tableWidget_2.verticalHeaderItem(20)
        item.setText(_translate("FlightOptionsWindow", "21."))
        item = self.tableWidget_2.verticalHeaderItem(21)
        item.setText(_translate("FlightOptionsWindow", "22."))
        item = self.tableWidget_2.verticalHeaderItem(22)
        item.setText(_translate("FlightOptionsWindow", "23."))
        item = self.tableWidget_2.verticalHeaderItem(23)
        item.setText(_translate("FlightOptionsWindow", "24."))
        item = self.tableWidget_2.verticalHeaderItem(24)
        item.setText(_translate("FlightOptionsWindow", "25."))
        item = self.tableWidget_2.verticalHeaderItem(25)
        item.setText(_translate("FlightOptionsWindow", "26."))
        item = self.tableWidget_2.verticalHeaderItem(26)
        item.setText(_translate("FlightOptionsWindow", "27."))
        item = self.tableWidget_2.verticalHeaderItem(27)
        item.setText(_translate("FlightOptionsWindow", "28."))
        item = self.tableWidget_2.verticalHeaderItem(28)
        item.setText(_translate("FlightOptionsWindow", "29."))
        item = self.tableWidget_2.verticalHeaderItem(29)
        item.setText(_translate("FlightOptionsWindow", "30."))
        item = self.tableWidget_2.verticalHeaderItem(30)
        item.setText(_translate("FlightOptionsWindow", "31."))
        item = self.tableWidget_2.verticalHeaderItem(31)
        item.setText(_translate("FlightOptionsWindow", "32."))
        item = self.tableWidget_2.verticalHeaderItem(32)
        item.setText(_translate("FlightOptionsWindow", "33."))
        item = self.tableWidget_2.verticalHeaderItem(33)
        item.setText(_translate("FlightOptionsWindow", "34."))
        item = self.tableWidget_2.verticalHeaderItem(34)
        item.setText(_translate("FlightOptionsWindow", "35."))
        item = self.tableWidget_2.verticalHeaderItem(35)
        item.setText(_translate("FlightOptionsWindow", "36."))
        item = self.tableWidget_2.verticalHeaderItem(36)
        item.setText(_translate("FlightOptionsWindow", "37."))
        item = self.tableWidget_2.verticalHeaderItem(37)
        item.setText(_translate("FlightOptionsWindow", "38."))
        item = self.tableWidget_2.verticalHeaderItem(38)
        item.setText(_translate("FlightOptionsWindow", "39."))
        item = self.tableWidget_2.verticalHeaderItem(39)
        item.setText(_translate("FlightOptionsWindow", "40."))
        item = self.tableWidget_2.verticalHeaderItem(40)
        item.setText(_translate("FlightOptionsWindow", "41."))
        item = self.tableWidget_2.verticalHeaderItem(41)
        item.setText(_translate("FlightOptionsWindow", "42."))
        item = self.tableWidget_2.verticalHeaderItem(42)
        item.setText(_translate("FlightOptionsWindow", "43."))
        item = self.tableWidget_2.verticalHeaderItem(43)
        item.setText(_translate("FlightOptionsWindow", "44."))
        item = self.tableWidget_2.verticalHeaderItem(44)
        item.setText(_translate("FlightOptionsWindow", "45."))
        item = self.tableWidget_2.verticalHeaderItem(45)
        item.setText(_translate("FlightOptionsWindow", "46."))
        item = self.tableWidget_2.verticalHeaderItem(46)
        item.setText(_translate("FlightOptionsWindow", "47."))
        item = self.tableWidget_2.verticalHeaderItem(47)
        item.setText(_translate("FlightOptionsWindow", "48."))
        item = self.tableWidget_2.verticalHeaderItem(48)
        item.setText(_translate("FlightOptionsWindow", "49."))
        item = self.tableWidget_2.verticalHeaderItem(49)
        item.setText(_translate("FlightOptionsWindow", "50."))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("FlightOptionsWindow", "Depart. From"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("FlightOptionsWindow", "Depart. Time"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("FlightOptionsWindow", "Arrival At"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("FlightOptionsWindow", "Arrival Time"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("FlightOptionsWindow", "Aircraft No."))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("FlightOptionsWindow", "Travel Class"))

