# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchcustomers.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SearchCustWindow(object):
    def setupUi(self, SearchCustWindow):
        SearchCustWindow.setObjectName("SearchCustWindow")
        SearchCustWindow.resize(603, 343)
        self.centralwidget = QtWidgets.QWidget(SearchCustWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 60, 691, 251))
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 20, 251, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        SearchCustWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SearchCustWindow)
        self.statusbar.setObjectName("statusbar")
        SearchCustWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(SearchCustWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 603, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuCustomers = QtWidgets.QMenu(self.menuBar)
        self.menuCustomers.setObjectName("menuCustomers")
        SearchCustWindow.setMenuBar(self.menuBar)
        self.actionAdd_New_Customer = QtWidgets.QAction(SearchCustWindow)
        self.actionAdd_New_Customer.setObjectName("actionAdd_New_Customer")
        self.actionUpdate_An_Existing_Customer = QtWidgets.QAction(SearchCustWindow)
        self.actionUpdate_An_Existing_Customer.setObjectName("actionUpdate_An_Existing_Customer")
        self.actionDelete_A_Customer = QtWidgets.QAction(SearchCustWindow)
        self.actionDelete_A_Customer.setObjectName("actionDelete_A_Customer")
        self.actionGo_Back_To_Main_Window = QtWidgets.QAction(SearchCustWindow)
        self.actionGo_Back_To_Main_Window.setObjectName("actionGo_Back_To_Main_Window")
        self.menuCustomers.addAction(self.actionAdd_New_Customer)
        self.menuCustomers.addAction(self.actionUpdate_An_Existing_Customer)
        self.menuCustomers.addAction(self.actionDelete_A_Customer)
        self.menuCustomers.addAction(self.actionGo_Back_To_Main_Window)
        self.menuBar.addAction(self.menuCustomers.menuAction())

        self.retranslateUi(SearchCustWindow)
        QtCore.QMetaObject.connectSlotsByName(SearchCustWindow)

    def retranslateUi(self, SearchCustWindow):
        _translate = QtCore.QCoreApplication.translate
        SearchCustWindow.setWindowTitle(_translate("SearchCustWindow", "MainWindow"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("SearchCustWindow", "Customer1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("SearchCustWindow", "Customer2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("SearchCustWindow", "Customer3"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("SearchCustWindow", "Customer Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("SearchCustWindow", "Cust. Travel ID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("SearchCustWindow", "Cust. Father\'s Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("SearchCustWindow", "Customer DOB"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("SearchCustWindow", "Cust. Tel. Number"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("SearchCustWindow", "Customer Address"))
        self.label.setText(_translate("SearchCustWindow", "All Clients Here!"))
        self.menuCustomers.setTitle(_translate("SearchCustWindow", "Customers"))
        self.actionAdd_New_Customer.setText(_translate("SearchCustWindow", "Add New Customer"))
        self.actionUpdate_An_Existing_Customer.setText(_translate("SearchCustWindow", "Update An Existing Customer"))
        self.actionDelete_A_Customer.setText(_translate("SearchCustWindow", "Delete A Customer"))
        self.actionGo_Back_To_Main_Window.setText(_translate("SearchCustWindow", "Go Back To Main Window"))

